### ISSUE TITLE
[Installation] Build fails on current version 0.0.0.1

### ISSUE THREAD

**Issue by natolambert** [huggingface/simulate#263]
When installing with `pip install simulate` on version 0.0.0.1, the following error is raised.

```
Collecting simulate
  Downloading simulate-0.0.0.1.tar.gz (171 kB)
     |████████████████████████████████| 171 kB 6.5 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/nato/miniconda3/envs/home/bin/python /Users/nato/miniconda3/envs/home/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/5_/bct76xnj7815tfx8xm7qxv6w0000gn/T/tmpd3ghu6y3
       cwd: /private/var/folders/5_/bct76xnj7815tfx8xm7qxv6w0000gn/T/pip-install-n2b9ugyk/simulate_1378accd61c84d4686d7282582f3daa1
  Complete output (23 lines):
  Traceback (most recent call last):
    File "/Users/nato/miniconda3/envs/home/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/Users/nato/miniconda3/envs/home/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/nato/miniconda3/envs/home/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/5_/bct76xnj7815tfx8xm7qxv6w0000gn/T/pip-build-env-mxs1zojk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/private/var/folders/5_/bct76xnj7815tfx8xm7qxv6w0000gn/T/pip-build-env-mxs1zojk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/5_/bct76xnj7815tfx8xm7qxv6w0000gn/T/pip-build-env-mxs1zojk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 482, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/5_/bct76xnj7815tfx8xm7qxv6w0000gn/T/pip-build-env-mxs1zojk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 131, in <module>
    File "/private/var/folders/5_/bct76xnj7815tfx8xm7qxv6w0000gn/T/pip-build-env-mxs1zojk/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 970, in cythonize
      module_list, module_metadata = create_extension_list(
    File "/private/var/folders/5_/bct76xnj7815tfx8xm7qxv6w0000gn/T/pip-build-env-mxs1zojk/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "/private/var/folders/5_/bct76xnj7815tfx8xm7qxv6w0000gn/T/pip-build-env-mxs1zojk/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
      raise ValueError(error_msg)
  ValueError: 'src/simulate/assets/procgen/wfc/core/wfc_binding.pyx' doesn't match any files
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/65/e5/fb46dda95838127aca7583867b6ed2ded47da6523d93e478490daa2c7889/simulate-0.0.0.1.tar.gz#sha256=055decdc9b5fb204a68f1301826327864fd3ffd8fed1bcf5c2b494635f8cd8e6 (from https://pypi.org/simple/simulate/). Command errored out with exit status 1: /Users/nato/miniconda3/envs/home/bin/python /Users/nato/miniconda3/envs/home/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/5_/bct76xnj7815tfx8xm7qxv6w0000gn/T/tmpd3ghu6y3 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement simulate (from versions: 0.0.0.1)
ERROR: No matching distribution found for simulate
```

**Comment by natolambert** [comment]
Resolved in release `0.0.1`
This was caused by the Cythonization of WFC. Currently removed temporarily.
